export default {
  data() {
    return {
      ionTags: [
        { tag: "div", label: "div" },
        { tag: "p", label: "p" },
        { tag: "IonContent", label: "IonContent" },
        { tag: "IonCard", label: "IonCard" },
        { tag: "IonCardHeader", label: "IonCardHeader" },
        { tag: "IonCardTitle", label: "IonCardTitle", noCR: "yes" },
        { tag: "IonCardSubtitle", label: "IonCardSubtitle", noCR: "yes" },
        { tag: "IonCardContent", label: "IonCardContent" },
        { tag: "IonItem", label: "IonItem" },
        { tag: "IonIcon", label: "IonIcon" },
        { tag: "IonLabel", label: "IonLabel" },
        { tag: "IonButton", label: "IonButton" },
        { tag: "IonImg", label: "IonImg" },
      ],
      ionIcons: [
        "add-circle-outline",
        "add-circle",
        "add",
        "airplane",
        "alarm",
        "albums",
        "alert",
        "american-football",
        "analytics",
        "aperture",
        "apps",
        "appstore",
        "archive",
        "arrow-back",
        "arrow-down",
        "arrow-dropdown-circle",
        "arrow-dropdown",
        "arrow-dropleft-circle",
        "arrow-dropleft",
        "arrow-dropright-circle",
        "arrow-dropright",
        "arrow-dropup-circle",
        "arrow-dropup",
        "arrow-forward",
        "arrow-round-back",
        "arrow-round-down",
        "arrow-round-forward",
        "arrow-round-up",
        "arrow-up",
        "at",
        "attach",
        "backspace",
        "barcode",
        "baseball",
        "basket",
        "basketball",
        "battery-charging",
        "battery-dead",
        "battery-full",
        "beaker",
        "bed",
        "beer",
        "bicycle",
        "bluetooth",
        "boat",
        "body",
        "bonfire",
        "book",
      ],
    };
  },
  methods: {
    ionAttributeArrangement: function (targetIonTag, newIonTag) {
      if (targetIonTag.noCR) {
        delete targetIonTag.noCR;
      }
      if (newIonTag.noCR) {
        targetIonTag["noCR"] = newIonTag.noCR;
      }
    },
  },
};
